/**
 * Auto-generated from vendor/.../matchnames/effects/firstparty.md
 * Do not edit by hand — run: npm run docs:allowlist
 */
export const FIRST_PARTY_EFFECT_MATCH_NAMES: readonly string[] = [
  "ADBE 3D Glasses",
  "ADBE 3D Glasses2",
  "ADBE 3D Tracker",
  "ADBE 4ColorGradient",
  "ADBE AIF Perlin Noise 3D",
  "ADBE Alpha Levels2",
  "ADBE Alpha Levels3",
  "ADBE Angle Control",
  "ADBE Apply Color LUT",
  "ADBE Apply Color LUT2",
  "ADBE Arithmetic",
  "ADBE ATG Extract",
  "ADBE Aud BT",
  "ADBE Aud Delay",
  "ADBE Aud HiLo",
  "ADBE Aud Modulator",
  "ADBE Aud Reverb",
  "ADBE Aud Reverse",
  "ADBE Aud Stereo Mixer",
  "ADBE Aud Tone",
  "ADBE Aud_Flange",
  "ADBE AudSpect",
  "ADBE AudWave",
  "ADBE AutoColor",
  "ADBE AutoContrast",
  "ADBE AutoLevels",
  "ADBE AUX CHANNEL EXTRACT",
  "ADBE Basic 3D",
  "ADBE Basic Text2",
  "ADBE Bevel Alpha",
  "ADBE Bevel Edges",
  "ADBE BEZMESH",
  "ADBE Bilateral",
  "ADBE Black&White",
  "ADBE Blend",
  "ADBE Block Dissolve",
  "ADBE Box Blur",
  "ADBE Box Blur2",
  "ADBE Brightness & Contrast",
  "ADBE Brightness & Contrast 2",
  "ADBE Broadcast Colors",
  "ADBE Brush Strokes",
  "ADBE Bulge",
  "ADBE Calculations",
  "ADBE Camera Lens Blur",
  "ADBE CameraShakeDeblur",
  "ADBE Cartoonify",
  "ADBE Cell Pattern",
  "ADBE Change Color",
  "ADBE Change To Color",
  "ADBE Channel Blur",
  "ADBE Channel Combiner",
  "ADBE CHANNEL MIXER",
  "ADBE Checkbox Control",
  "ADBE Checkerboard",
  "ADBE Cineon Converter",
  "ADBE Cineon Converter2",
  "ADBE Circle",
  "ADBE Color Balance",
  "ADBE Color Balance (HLS)",
  "ADBE Color Balance 2",
  "ADBE Color Control",
  "ADBE Color Difference Key",
  "ADBE Color Emboss",
  "ADBE Color Key",
  "ADBE Color Link",
  "ADBE Color Range",
  "ADBE Compander",
  "ADBE Compound Arithmetic",
  "ADBE Compound Blur",
  "ADBE Corner Pin",
  "ADBE CurvesCustom",
  "ADBE Deflicker",
  "ADBE DEPTH FIELD",
  "ADBE DEPTH MATTE",
  "ADBE Difference",
  "ADBE Difference Matte2",
  "ADBE Displacement Map",
  "ADBE Drop Shadow",
  "ADBE Dropdown Control",
  "ADBE Dust & Scratches",
  "ADBE Easy Levels",
  "ADBE Easy Levels2",
  "ADBE Echo",
  "ADBE ELLIPSE",
  "ADBE Emboss",
  "ADBE Equalize",
  "ADBE Exposure",
  "ADBE Exposure2",
  "ADBE Extract",
  "ADBE Eyedropper Fill",
  "ADBE Fast Blur",
  "ADBE Fill",
  "ADBE Find Edges",
  "ADBE FOG_3D",
  "ADBE Fractal",
  "ADBE Fractal Noise",
  "ADBE FreePin3",
  "ADBE Gamma/Pedestal/Gain2",
  "ADBE Gaussian Blur",
  "ADBE Gaussian Blur 2",
  "ADBE Geometry",
  "ADBE Geometry2",
  "ADBE Glo2",
  "ADBE Gradient Wipe",
  "ADBE Grid",
  "ADBE GROW BOUNDS",
  "ADBE HDR ToneMap",
  "ADBE HUE SATURATION",
  "ADBE ID MATTE",
  "ADBE Invert",
  "ADBE IRIS_WIPE",
  "ADBE KeyCleaner",
  "ADBE Laser",
  "ADBE Layer Control",
  "ADBE Leave Color",
  "ADBE Lens Flare",
  "ADBE Lightning",
  "ADBE Lightning 2",
  "ADBE Linear Color Key2",
  "ADBE Linear Wipe",
  "ADBE LIQUIFY",
  "ADBE Luma Key",
  "ADBE Lumetri",
  "ADBE Magnify",
  "ADBE Matte Choker",
  "ADBE Median",
  "ADBE MESH WARP",
  "ADBE Minimax",
  "ADBE Mirror",
  "ADBE Mosaic",
  "ADBE Motion Blur",
  "ADBE Noise",
  "ADBE Noise Alpha",
  "ADBE Noise Alpha2",
  "ADBE Noise HLS",
  "ADBE Noise HLS Auto",
  "ADBE Noise HLS Auto2",
  "ADBE Noise HLS2",
  "ADBE Numbers2",
  "ADBE Offset",
  "ADBE OFMotionBlur",
  "ADBE Optics Compensation",
  "ADBE Paint",
  "ADBE Paint Bucket",
  "ADBE Param EQ",
  "ADBE Path Text",
  "ADBE Photo Filter",
  "ADBE PhotoFilterPS",
  "ADBE Playgnd",
  "ADBE Point Control",
  "ADBE Point3D Control",
  "ADBE Polar Coordinates",
  "ADBE Posterize",
  "ADBE Posterize Time",
  "ADBE Pro Levels",
  "ADBE Pro Levels2",
  "ADBE ProfileToProfile",
  "ADBE PS Arbitrary Map",
  "ADBE PSL Bevel Emboss",
  "ADBE PSL Drop Shadow",
  "ADBE PSL Inner Glow",
  "ADBE PSL Inner Shadow",
  "ADBE PSL Outer Glow",
  "ADBE PSL Solid Fill",
  "ADBE Radial Blur",
  "ADBE Radial Shadow",
  "ADBE Radial Wipe",
  "ADBE Ramp",
  "ADBE Reduce Interlace Flicker",
  "ADBE RefineMatte",
  "ADBE RefineMatte2",
  "ADBE RefineRBMatte",
  "ADBE Remove Color Matting",
  "ADBE RESHAPE",
  "ADBE Ripple",
  "ADBE Rolling Shutter",
  "ADBE Roughen Edges",
  "ADBE Samurai",
  "ADBE Scatter",
  "ADBE SCHMEAR",
  "ADBE Scribble Fill",
  "ADBE SelectiveColor",
  "ADBE Set Channels",
  "ADBE Set Matte2",
  "ADBE Set Matte3",
  "ADBE ShadowHighlight",
  "ADBE Sharpen",
  "ADBE Shift Channels",
  "ADBE Simple Choker",
  "ADBE Slider Control",
  "ADBE Smart Blur",
  "ADBE Solid Composite",
  "ADBE Spherize",
  "ADBE Spill Suppressor",
  "ADBE Spill2",
  "ADBE Strobe",
  "ADBE Stroke",
  "ADBE SubspaceStabilizer",
  "ADBE Texturize",
  "ADBE Three-Way Color Corrector",
  "ADBE Threshold",
  "ADBE Threshold2",
  "ADBE Tile",
  "ADBE Time Displacement",
  "ADBE Timecode",
  "ADBE Timewarp",
  "ADBE Tint",
  "ADBE Tritone",
  "ADBE Turbulent Displace",
  "ADBE Twirl",
  "ADBE Unsharp Mask",
  "ADBE Unsharp Mask2",
  "ADBE Upscale",
  "ADBE Vector Paint",
  "ADBE Venetian Blinds",
  "ADBE Vibrance",
  "ADBE Wave Warp",
  "ADBE Write-on",
  "ADBE WRPMESH",
  "APC CardDanceCam",
  "APC CardWipeCam",
  "APC Caustics",
  "APC Colorama",
  "APC Foam",
  "APC Radio Waves",
  "APC Shatter",
  "APC Vegas",
  "APC Wave World",
  "CC Ball Action",
  "CC Bend It",
  "CC Bender",
  "CC Blobbylize",
  "CC Bubbles",
  "CC Burn Film",
  "CC Color Offset",
  "CC Composite",
  "CC Cylinder",
  "CC Drizzle",
  "CC Environment",
  "CC Flo Motion",
  "CC Force Motion Blur",
  "CC Glass",
  "CC Glass Wipe",
  "CC Glue Gun",
  "CC Grid Wipe",
  "CC Griddler",
  "CC Hair",
  "CC Image Wipe",
  "CC Jaws",
  "CC Kaleida",
  "CC Lens",
  "CC Light Burst 2.5",
  "CC Light Rays",
  "CC Light Sweep",
  "CC Light Wipe",
  "CC Mr. Mercury",
  "CC Mr. Smoothie",
  "CC Overbrights",
  "CC Page Turn",
  "CC Particle Systems II",
  "CC Particle World",
  "CC Pixel Polly",
  "CC Plastic",
  "CC Power Pin",
  "CC PS Classic",
  "CC PS LE Classic",
  "CC Radial Blur",
  "CC Radial Fast Blur",
  "CC Radial ScaleWipe",
  "CC Rain",
  "CC RepeTile",
  "CC Ripple Pulse",
  "CC Scale Wipe",
  "CC Scatterize",
  "CC Simple Wire Removal",
  "CC Slant",
  "CC Smear",
  "CC Snow",
  "CC Sphere",
  "CC Split",
  "CC Split 2",
  "CC Spotlight",
  "CC Star Burst",
  "CC Threshold",
  "CC Threshold RGB",
  "CC Tiler",
  "CC Time Blend",
  "CC Time Blend FX",
  "CC Toner",
  "CC Twister",
  "CC Vector Blur",
  "CC WarpoMatic",
  "CC Wide Time",
  "CINEMA 4D Effect",
  "CS BlockLoad",
  "CS Color Neutralizer",
  "CS CrossBlur",
  "CS HexTile",
  "CS Kernel",
  "CS LineSweep",
  "CS Threads",
  "CS Vignette",
  "CSRainfall",
  "CSSnowfall",
  "EXtractoR",
  "IDentifier",
  "ISL MochaShapeImporter",
  "Keylight 906",
  "SYNTHAP CF Color Finesse 2",
  "VISINF Grain Duplication",
  "VISINF Grain Implant",
  "VISINF Grain Removal",
];
